name: BottledExp
version: ${project.version}
api-version: '1.21'
description: Fills the player's XP into a bottle
author: sacnoth, Error110

main: me.sacnoth.bottledexp.BottledExp

permissions:
   bottle.use:
      description: Allows the user to do /bottle [total]
      default: op
   bottle.max:
      description: Allows the user to do /bottle max
      default: op
   bottle.reload:
      description: Allows the user to do /bottle reload reloading the config
      default: op

commands:
   bottle:
      description: Fills XP into a bottle.
      usage: /bottle [amount]
      permission: bottle.use
      permission-message: You don't have permission to do this