name: BottledExp
version: ${project.version}
api-version: '1.21'
description: Fills the player's XP into a bottle
author: sacnoth, Error110
website: http://www.bukkit.org

main: me.sacnoth.bottledexp.BottledExp
database: false
softdepend: [Vault]

commands:
   bottle:
      description: Fills XP into a bottle.
      usage: /<command> [amount]
      permission-message: You don't have permission to do this